name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up g++
        run: sudo apt-get install g++

      - name: Compile main.cpp and test.cpp
        run: |
          g++ main.cpp test.cpp
          
      - name: check files 
        run: ls -l

      - name: Run tests
        run: ./main
